# Below is an example of a game code patch, done using lovely.
# Check their documentation for details.

[manifest]
version = "1.0.0"
priority = 0

# This patch comments out the LONG DT message in vanilla Balatro.

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if self.real_dt > 0.05 then print('LONG DT @ '..math.floor(G.TIMERS.REAL)..': '..self.real_dt) end"
position = "before"
payload = '''--[['''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if self.real_dt > 0.05 then print('LONG DT @ '..math.floor(G.TIMERS.REAL)..': '..self.real_dt) end"
position = "after"
payload = ''']]'''
match_indent = true
times = 1